# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r23c

    - name: Install UPX
      run: |
        sudo apt-get update
        sudo apt-get install -y upx

    - name: Build
      run: |
        export ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}
        export GO111MODULE=on
        ./build-android.sh $(cat frpVersion.txt)

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: $(cat frpVersion.txt)
          release_name: Auto Release $(cat frpVersion.txt)
          draft: true
          prerelease: false

    - name: Upload files
      run: |
        for file in frp/bin/upx/*; do
          if [[ -f ${file} ]]; then
              echo "Uploading $file"
              gh release upload ${{ github.ref }} "$file" --repo ${{ github.repository }}
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
